### ISSUE TITLE
Cache doesnt work on Sony Xperia M2

### ISSUE THREAD

**Issue by ghost** [null-dev/animeopenings-android#5]
Just like the Title says, it doesnt work!
Even on Experiment Build!

**Comment by null-dev** [comment]
Yes, I know the cache is not working properly on any of the builds. It's extremely slow and buggy. It appears to be a problem with this: https://github.com/danikula/AndroidVideoCache.

Either way, AndroidVideoCache has updated so I'm not sure if the issues have been fixed yet. I'll update the dependencies and check again.

I've also been very busy lately which is why there have been no updates for this app in a long time.

**Comment by null-dev** [comment]
Nevermind, bug found and isolated, fix in progress.

I'll try to release a new version today with the fix.

**Comment by null-dev** [comment]
If you want, you can find a version with the fix here: http://cirelease.nulldev.xyz/servefile.php?path=/build/ao-brmaster-cofd78403255c0dade1d8eb20b37cf205414f943f1-bu52.apk
